name = "d1-auth-example"
main = "src/index.ts"
compatibility_date = "2024-09-01"


[[d1_databases]]
binding = "DB"
database_name = "wroker-users"
database_id = "4ca352e9-029f-4767-b749-1efbc319b773"


[vars]
SALT_TOKEN = "sadfasdghjyt45645t"
